# Generated by Django 2.1 on 2018-08-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgboard', '0003_auto_20180805_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='post_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
