# Generated by Django 2.1 on 2018-08-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgboard', '0004_auto_20180805_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='is_dislike',
        ),
        migrations.RemoveField(
            model_name='record',
            name='is_like',
        ),
    ]
