# Generated by Django 2.1 on 2018-08-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgboard', '0005_auto_20180805_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
